### PR TITLE
update config.guess

### PR DESCRIPTION
**Pull request by kazuho**
Current version of config.guess is too old that it fails to detect aarch64.

This PR updates the file to the most recent version; obtained from http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD

### CODE REVIEW

**Comment by k-takata** [comment]
Sorry for the late response.
Is this file already released? I think it's better to use a release version.
Does this version support ppc64el? (see #61)
(Or should we obtain more resent version?)

**Comment by kazuho** [comment]
> Is this file already released? I think it's better to use a release version.

I am not sure.  Looking at http://git.savannah.gnu.org/gitweb/?p=config.git;a=summary I wonder if there is a separate _release_ process for config.guess.

> Does this version support ppc64el? (see #61)

I believe so, considering the fact that it refers to `ppc64le`.

**Comment by k-takata** [comment]
I thought `config.guess` and `config.sub` were part of automake, but it seems wrong(?).
Is it okay to update only `config.guess`? No need to update `config.sub`?

memo:
`config.guess` which comes with automake-1.15 has a timestamp '2014-12-03' (older than this PR).
It seems to support both aarch64 and ppc64le.

**Comment by kazuho** [comment]
FYI https://www.gnu.org/software/automake/manual/html_node/Auxiliary-Programs.html states that _each new release of Automake comes with up-to-date copies of these programs. If your copy of Automake is getting old, you are encouraged to fetch the latest versions of these files from http://savannah.gnu.org/git/?group=config before making a release._

So I think updating both config.guess and config.sub to the ones found on Git to be the right solution.

**Comment by k-takata** [comment]
> So I think updating both config.guess and config.sub to the ones found on Git to be the right solution.

Thank you for the information.
Could you update the PR to include updated config.guess and config.sub?

**Comment by k-takata** [comment]
Sorry for the very late response. Fixed with 8f2b7c5dcf7cd3e1ec54ab8f23376d2ccd77c896.

**Pull request closed without merging**
