### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/k-takata/Onigmo/ci/#badges) to your project. They indicate how you care about code quality and encourage your future contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/k-takata/Onigmo).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by k-takata** [comment]
Thank you.

**Comment by xcorail** [comment]
Hi @k-takata 
Happy you found it useful!
Some precisions: 
At the moment, LGTM polls your repo once a day, and analyzes all new commits, most recent first.
I recommend to activate automated code review: LGTM will analyze the Pull Requests **immediately** and report any new problem in the comments, before they reach your master. It's free for public open source projects, and it's a [one click operation](https://lgtm.com/projects/g/k-takata/Onigmo/ci/)

Cheers

**Comment by k-takata** [comment]
Hi @xcorail,

> I recommend to activate automated code review:

Does it affect only this repository or all repositories I have? Can I activate LGTM selectively on my each repository?
Does it also affect to the GitHub organization which I attend?
GitHub's authorization page shows that LGTM is requesting Organization access.

**Comment by xcorail** [comment]
Hello @k-takata 
>Does it affect only this repository or all repositories I have? Can I activate LGTM selectively on my each repository?

The integration is done **per repository**. Not for all repos at once.

>Does it also affect to the GitHub organization which I attend? GitHub's authorization page shows that LGTM is requesting Organization access.

LGTM doesn't need access to your organization and does not impact it. But if your repository has [OAuth Apps access restrictions enabled](https://help.github.com/articles/about-oauth-app-access-restrictions/), a member cannot authorize an app to access any of the organization resource, he needs to first [request the organization's approval](https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/). More details in our [help](https://lgtm.com/help/lgtm/managing-automated-code-review)

On the same note, here are the OAuth scopes required by LGTM:

- **Access commit status**: So that we can update the commit status when pull requests are opened
- **Access public repositories**: We use this scope to post comments on pull requests as the authenticated user when a pull request introduces or fixes alerts.
- **Write repository hooks**: Allows us to set up the initial webhook so that GitHub will notify LGTM whenever a pull request is opened or modified. 

But we won't actually write anything in your repo, we'll just post comments. We are in the process of transitioning our GitHub integration to use GitHub Apps (it's on 2019 Q1 plan), and these OAuth permissions will not be necessary once people start using that.

Cheers

**Pull request merged**
